name: bs-pvpcage
main: net.robbytu.banjoserver.pvpcage.Main
version: ${version}
depends: [Vault, WorldEdit]
commands:
  pvpcage:
    description: bs-pvpcage config management
    permission:
    usage: /pvpcage [<create/remove/info> <name>/<require/prohibit> <add/remove> <name> <item>]